### ISSUE TITLE
which dictionary

### ISSUE THREAD

**Issue by bsbhro** [pinae/DeepL-Console-Translator#1]
Hi, only a question. Using the website https://www.deepl.com/translator, the english 'siege' is translated correctly to german 'Belagerung'. Using the console it is translated to 'triumph'. German 'Sieg' and 'Siege' is english 'triumph'. I write 'translate.py -l DE siege' and get triumph; it should be Belagerung.

**Comment by bermeitinger-b** [comment]
This is due to the fact, that the request is using `auto` for letting DeepL decide on the source language. For the word 'siege' it detects German and translates it to the English 'triumph'.

You can see in #3  that I added an option to manually define source and target language.
`./translate.py -s EN -t DE 'siege'` → `Belagerung`

**Comment by chriskonnertz** [comment]
Yes, that makes sense since "siege" is the imperative of "siegen" (to win). It is an ambiguity and DeepL makes its choice.

**Comment by pinae** [comment]
I believe this is solved after @bermeitinger-b added language options.
